config/routes.rb
Rails.application.routes.draw do
  resources :app_settings
  devise_for :users, controllers: { registrations: 'user_registrations/registrations' }
  resources :template_ones
  
  root to: 'template_ones#index'

  resources :posts do
    resources :comments
  end
end

app/models/template_one.rb
class TemplateOne < ApplicationRecord
end

app/controllers/template_ones_controller.rb
class TemplateOnesController < ApplicationController
  before_action :set_template_one, only: [:show, :edit, :update, :destroy]

  # GET /template_ones
  # GET /template_ones.json
  def index
    @template_ones = TemplateOne.all
  end

  # GET /template_ones/1
  # GET /template_ones/1.json
  def show
  end

  # GET /template_ones/new
  def new
    @template_one = TemplateOne.new
  end

  # GET /template_ones/1/edit
  def edit
  end

  # POST /template_ones
  # POST /template_ones.json
  def create
    @template_one = TemplateOne.new(template_one_params)

    respond_to do |format|
      if @template_one.save
        format.html { redirect_to @template_one, notice: 'Template one was successfully created.' }
        format.json { render :show, status: :created, location: @template_one }
      else
        format.html { render :new }
        format.json { render json: @template_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /template_ones/1
  # PATCH/PUT /template_ones/1.json
  def update
    respond_to do |format|
      if @template_one.update(template_one_params)
        format.html { redirect_to @template_one, notice: 'Template one was successfully updated.' }
        format.json { render :show, status: :ok, location: @template_one }
      else
        format.html { render :edit }
        format.json { render json: @template_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /template_ones/1
  # DELETE /template_ones/1.json
  def destroy
    @template_one.destroy
    respond_to do |format|
      format.html { redirect_to template_ones_url, notice: 'Template one was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template_one
      @template_one = TemplateOne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def template_one_params
      params.require(:template_one).permit(:string_input_1)
    end
end

app/helpers/template_ones_helper.rb
module TemplateOnesHelper
end

app/views/template_ones/_form.html.erb
<%= simple_form_for(@template_one) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :string_input_1 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/template_ones/edit.html.erb
<h1>Editing Template One</h1>

<%= render 'form', template_one: @template_one %>

<%= link_to 'Show', @template_one %> |
<%= link_to 'Back', template_ones_path %>

app/views/template_ones/index.html.erb
<h1>Template Ones</h1>

<table>
  <thead>
    <tr>
      <th>String input 1</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @template_ones.each do |template_one| %>
      <tr>
        <td><%= template_one.string_input_1 %></td>
        <td><%= link_to 'Show', template_one %></td>
        <td><%= link_to 'Edit', edit_template_one_path(template_one) %></td>
        <td><%= link_to 'Destroy', template_one, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template One', new_template_one_path %>

app/views/template_ones/new.html.erb
<h1>New Template One</h1>

<%= render 'form', template_one: @template_one %>

<%= link_to 'Back', template_ones_path %>

app/views/template_ones/show.html.erb
<p>
  <strong>String input 1:</strong>
  <%= @template_one.string_input_1 %>
</p>

<%= link_to 'Edit', edit_template_one_path(@template_one) %> |
<%= link_to 'Back', template_ones_path %>