config/routes.rb
Rails.application.routes.draw do
  resources :app_settings
  devise_for :users, controllers: { registrations: 'user_registrations/registrations' }
  resources :template_ones
  
  root to: 'template_ones#index'

  resources :posts do
    resources :comments
  end
end

app/views/layouts/navigation_bootswatch/_navbar.html.erb
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'My App', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <%= link_to 'Posts', posts_path, class: 'nav-link' %>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li>

<% if current_user %> 
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">
            Admin Menu
            <span class="caret"></span></a>
            <div class="dropdown-menu" aria-labelledby="download">
            <%= link_to 'App Settings', app_setting_path(@app_setting), class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
                Link
            </div>
        </li>
<% end %>

        </ul>
        <ul class="nav navbar-nav ml-auto">
<% if !current_user %>
        <%= link_to 'Create Account', new_user_registration_path, class: 'nav-link' %>
        <%= link_to 'Sign In', user_session_path, class: 'nav-link' %>
<% else %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">

            <%= current_user.username if current_user %>
            <span class="caret"></span></a>
            <div class="dropdown-menu" aria-labelledby="download">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
        </li>
<% end %>
    </ul>
    </div>
    </nav>
</div>